### ISSUE TITLE
[Enhancement] Return resource id when creating a resource

### ISSUE THREAD

**Issue by brumer** [keycloak/keycloak-nodejs-admin-client#11]
First thing i would like to thank you for this sdk, its really helpful!
When creating a resource (e.g user, group ,real etc..), the id of the newly created resource can be retrieved from the "Location" header in the response.
![image](https://user-images.githubusercontent.com/7696032/49445700-2ecebf80-f7db-11e8-8c0a-61e4bd8f3984.png)

can you alter the create functions to return the id?

**Comment by wwwy3y3** [comment]
Sounds nice!

Didn't notice the location has information like this.

I'll be sure to add this feature

**Comment by wwwy3y3** [comment]
hi, @brumer and people who thumb up ( @metametadata , @TimothySealy).

This feature request is supported at `v1.12.0`.

You can now get the id of created resource in the response.

For example:
```ts
const group = await this.kcAdminClient.groups.create({
  name: 'cool-group',
});

console.log(group.id);
// print 72450d90-1ece-44c4-9690-c5c3146efa39
```

Resources including `Group`, `User`, `Realm`, `Client`, `Role` are all supported with this feature.

**Comment by metametadata** [comment]
`client.createRole()` seems to return only the name of the created role. So I have to call `clients.findRole()` next in order to retrieve the id of the created role.

Is this by design? Why not make `createRole` return the whole new object?

**Comment by wwwy3y3** [comment]
@metametadata it's because the restful api of keycloak gives me the role name in the location header instead of role id.
