### ISSUE TITLE
Move repository to Keycloak organization

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-nodejs-admin-client#12]
Creating an issue to link with https://github.com/keycloak/keycloak-admin-client/issues/81

The Keycloak team would welcome moving this repository to the Keycloak organization and keeping the Canner team as maintainers. We hope this would give you more visibility and more users as well as contributors.

**Comment by wwwy3y3** [comment]
Thanks, @stianst !

I already replied in keycloak/keycloak-admin-client#81.

Let's move on!
