### ISSUE TITLE
Authentication Management Api + Code Examples

### ISSUE THREAD

**Issue by rawc0der** [keycloak/keycloak-nodejs-admin-client#130]
**Is your feature request related to a problem? Please describe.**
I'm having issues finding the correct steps for creating an **Authentication-Flow** using the management-api. This is a more complicated part of the api and some official examples would be very useful besides the test files.

**Describe the solution you'd like**
This has just been recently added in #126 and the lack of examples is frustrating for many reasons, especially since there is a lot of effort in building integrations with Keycloak. _(think bootstrapping a realm after deployment) - lots of gaps here!!_

**Describe alternatives you've considered**
Besides using this officially supported keycloak client, I was able to generate a node client from [openapi schemas](https://github.com/ccouzens/keycloak-openapi), provided by the community and work with the AuthenticationApi which is very similar, but lacks examples and is hard to reverse-engineer.

**Additional context**
I have had a lot of hard time around the lack of support for the **AuthenticationManagement** - having a small example of loading an **AuthenticationFlow + Subflows / Executions and Actions** would bring a lot of clarity and bliss.

Thank you!

**Comment by edewit** [comment]
something like this?
https://gist.github.com/edewit/df87925ebb2c084f0d15052eb7e93ff2

**Comment by rawc0der** [comment]
Yes, this should be really helpful. 
Any chance of providing a flow creation from scratch? I know what executions I need, but nesting them in the subflows is what Im struggling with.
Thanks again!

**Comment by edewit** [comment]
by sub-flow you mean the level? You can "just" update the level of the execution to the level you need e.g.: `"level":1`

**Comment by edewit** [comment]
ahh no I know what you mean adding a flow to a existing flow, I think this is missing in this api

**Comment by edewit** [comment]
@rawc0der added in #131
