### ISSUE TITLE
Library is breaking NodeJS global object

### ISSUE THREAD

**Issue by bojanbass** [keycloak/keycloak-nodejs-admin-client#135]
Hi. 

In version 1.14.0 or greater there was a big issue introduced regarding manipulation NodeJS `global` object. The change was done here:
https://github.com/keycloak/keycloak-nodejs-admin-client/commit/205bfc12e907a8236b4c257a7c7555943f46d00e

Any other library that can work in browsers or NodeJs can break because in case when running in NodeJs it could detect `window` object and think it is running in the browser. A real example is Zone.js library, which crashes if `keycloak-admin` was loaded before.
https://github.com/angular/angular/blob/master/packages/zone.js/lib/zone.ts#L1441

My current workaround is to delete `global.window` property right after `keycloak-admin` is imported. Could you provide a better solution to this?

Thank you.

**Comment by dennismorello** [comment]
+1. This is breaking all Next.js apps in which `keycloak-admin` is used on the server.

**Comment by dennismorello** [comment]
I am missing the reason why this library should polyfill the `window` object 🤔

**Comment by bojanbass** [comment]
I suppose this is because it's using `keycloak-js` library in behind, which is a client side only I guess. It shouldn't be used this way.

**Comment by dennismorello** [comment]
Yes, it should not be used this way, I totally agree.

**Comment by dennismorello** [comment]
@abstractj @edewit any update on this? Thank you 😃

**Comment by edewit** [comment]
it's been fixed in #122 and released in version 1.14.5

**Comment by dennismorello** [comment]
> it's been fixed in #122 and released in version 1.14.5

I'm using version 1.14.8 and this issue is still present.

**Comment by edewit** [comment]
@dennismorello so what do you suggest?

**Comment by dennismorello** [comment]
I expect this lib to run in a Node.js app, so I would totally remove the fake `window` polyfill. If it causes incompatibilities with other dependencies, I would refactor the project in order to respect the Single Responsibility Principle.

**Comment by dennismorello** [comment]
I can fork the project and do some tests by myself.

**Comment by bojanbass** [comment]
Great, I've tested it and it works fine now.

**Comment by edewit** [comment]
cool thanks @bojanbass
