### ISSUE TITLE
logout-all doesn't invalidate tokens 

### ISSUE THREAD

**Issue by selimslab** [keycloak/keycloak-nodejs-admin-client#136]
**Describe the bug**
realms logout-all does not invalidate user sessions  

**To Reproduce**

Used the sample from [docs](https://github.com/keycloak/keycloak-nodejs-admin-client/blob/master/test/realms.spec.ts)

```js
      kcAdminClient = new KeycloakAdminClient();
      await kcAdminClient.auth(credentials);
      const logout = await kcAdminClient.realms.logoutAll({
        realm: currentRealmName,
      });
```

**Expected behavior**
After calling logout-all, old userToken should be invalid 

**Enviroment**
- OS MacOS
 - Keycloak Version 8.0.1
 - Library Version 1.14.0

**Comment by ath88** [comment]
What is the value of `logout` after the snippet? I'm curious about the response from the server.

**Comment by selimslab** [comment]
it's an empty object {}

**Comment by ath88** [comment]
@selimslab Was the problem solved?

**Comment by selimslab** [comment]
I was expecting the access token to be invalid after the session is removed 

Turns out  the access token is still valid after removing the session, and the client doesn't log out 

Solved by removing the token from client
