### ISSUE TITLE
Issue with the example provided to refresh the access token

### ISSUE THREAD

**Issue by slimovic** [keycloak/keycloak-nodejs-admin-client#15]
I am trying the example in the README to refresh the access token using the openid-client but unfortunately I'm not able to get the client working.

**To Reproduce**
1. Just run the example in the README 
2. After instantiating the client, I tried to console log the client and I'm getting  `{ CLOCK_TOLERANCE: 0 }`
3. And of course there is no `refreshToken`

`const client = new keycloakIssuer.Client({
  client_id: 'admin-cli',
  client_secret: 'wwwy3y3', 
});
console.log(client.refreshToken); // undefined
`

**Expected behavior**
The client must contains other properties like the refreshToken.

**Enviroment:**
 - OS: [Ubuntu/Windows]
 - Keycloak Version: I tried 3.4.3 and 4.8.0
 - Library Version [1.9.0]
 - NodeJs: v8.15.0 and with 10.15.1 I'm getting this warning: 

> (node:47720) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

 
**Additional context**
Am I missing something? Just not sure that the **client_secret** must contain a password or a real secret.
I know this is not fully related to this library, but it will be nice to make this example works.

**Comment by slimovic** [comment]
@karlhorky

**Comment by slimovic** [comment]
@wwwy3y3 I fixed the issue by using the grant 'password'

```javascript
// Use the grant type 'password'
let tokenSet = await client.grant({
  grant_type: 'password',
  username: 'wwwy3y3',
  password: 'wwwy3y3',
});
```

I made a PR to update the example in the README

**Comment by wwwy3y3** [comment]
@slimovic Thanks!

Close it due to #16

**Comment by justintime4tea** [comment]
I was having issues even with the latest changes described here. I had to use the refresh token from KcAdminClient.refreshToken instead of from the token set from openid-client. Not exactly sure why... 

In-case anyone stumbles upon this thread and finds themselves in the same position as I was in I thought I'd comment here.

Thanks for the amazing work.
