### ISSUE TITLE
How to abort a request?

### ISSUE THREAD

**Issue by netevolution** [keycloak/keycloak-nodejs-admin-client#153]
Hello,

I use your library in React. I would need to stop an ongoing request before disconnecting the component. How can I achieve this?

Ideally I would need to use something like here:
https://developers.google.com/web/updates/2017/09/abortable-fetch

**Comment by edewit** [comment]
@netevolution we use axios as the transport layer it does have something for aborting requests we should expose this in the API

**Comment by netevolution** [comment]
@edewit I also use Axios in my projects. Yes, you are right that there is such a possibility.
So can I expect this option to be available in your library?

Thank you for answer.

**Comment by edewit** [comment]
Yes, I'll add it...

**Comment by edewit** [comment]
or if you have a shared `KcAdminClient` somewhere use the `setConfig`:

```typescript
useEffect(() => {
  const source = axios.CancelToken.source();
  adminClient.setConfig({ requestConfig: { cancelToken: source.token } });

  try {
     const result = await adminClient.clients.find();
     setState(result);
   } catch(err) {
      if (!axios.isCancel(err)) {
        // handle error
      }
    }

  return () => {
    source.cancel();
  };
}
```
