### ISSUE TITLE
Method Addition: listCompositeClientRoleMappings under Users class

### ISSUE THREAD

**Issue by husoman** [keycloak/keycloak-nodejs-admin-client#159]
I need a method for getting User Composite Roles. In my opinion, related endpoint would be
**GET /{realm}/users/{id}/role-mappings/clients/{client}/composite** for such a method.
Please see "Get effective client-level role mappings" in the following link: 
https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_client_role_mappings_resource

**Comment by LRipi** [comment]
Closed by #158

**Comment by edewit** [comment]
ahhh yes thanks @LRipi. @husoman this is done and released in `1.14.12`
