### ISSUE TITLE
Bug: Missing Locale translation (German)

### ISSUE THREAD

**Issue by VijoPlays** [keycloak/keycloak-nodejs-admin-client#161]
**Describe the bug**
When using Keycloak's redirect to log into a web app, the locales work, but the German one is missing a translation.

**Expected behavior**
It should say something along the lines of "Melden Sie sich an" or "Melden Sie sich in Ihrem Konto an", instead of "Sign in to your account".

**Screenshots**
![Screenshot](https://i.imgur.com/2rOe7W5.png)

[Clickable screenshot](https://i.imgur.com/2rOe7W5.png)

**Comment by edewit** [comment]
@VijoPlays this should be a bug for the keycloak project and not the keycloak-nodejs-admin-client. I think the text should be "Bei Ihrem Konto anmelden" as defined in the `messages_de.properties` don't know why it doesn't work for the title

**Comment by VijoPlays** [comment]
Yeah, this is the only project I can create Issues in, so I just had to dump it in here

**Comment by edewit** [comment]
right keycloak doesn't use github issues but jira you can create an issue here: https://issues.redhat.com/projects/KEYCLOAK
