### ISSUE TITLE
npm package not associated with the github repository

### ISSUE THREAD

**Issue by Mimameid** [keycloak/keycloak-nodejs-admin-client#166]
The npm package is not associated with this repo. Nor is this repo associated with any npm package as far as I can tell.

I tried to figure out if this repository is published as an npm package. One would assume so, and it probably, as the link in the README hints, is. But I can't tell which of the packages I found is the official one.

The link in the README.md is broken, see: https://badge.fury.io/js/@keycloak/keycloak-admin-client

**Comment by edewit** [comment]
@Mimameid right we should fix this atm it's published in 2 places

1. https://www.npmjs.com/package/@keycloak/keycloak-admin-client
2. https://www.npmjs.com/package/keycloak-admin

The fist one is released together with that version of keycloak the second one is release at a quicker pace
