### ISSUE TITLE
[BUG] Composite roles are missing when creating a role

### ISSUE THREAD

**Issue by xCryzed** [keycloak/keycloak-nodejs-admin-client#168]
Unfortunately the composite roles are not saved when a role is created with the keycloak-admin module.

I'm calling the function:

`await kcAdminClient.roles.create(realmRole)` 

where realm role is the following object:

```
{
  name: 'user',
  description: 'description',
  clientRole: false,
  composite: true,
  composites: {
    client: {
      'my-service': [
        'my-service-read',
        'my-service-create',
        'my-service-update',
        'my-service-delete'
      ]
    }
  }
}
```

After the function call a realm role with the name user is created, but the composite boolean is false and there are no composite roles.

If I try afterwards to add the composite roles with:

```
await kcAdminClient.roles.createComposite({ roleId: role.id },
  [
    {
      composites: {
        client: {
          'my-service': [
               'my-service-read',
               'my-service-create',
               'my-service-update',
               'my-service-delete'
          ]
        }
      }
    }
  ]);
```

I get the following error:

```
[org.keycloak.services.error.KeycloakErrorHandler] (default task-44) Uncaught server error: java.lang.NullPointerException: Null keys are not supported!
```

**Additional info**

The client is also already created with the specified roles above.

**Enviroment:**
 - Windows 10
 - Keycloak version 12.0.4
 - Library Version 1.14.15
 - node version 15.12.0

**Comment by edewit** [comment]
You can't create a composite role on creation, this api is close to what the admin console does. So have a look how to create composite roles there.

You create a role first:
```typescript
      const currentRole = await client.roles.create({
        name: "user",
      });
```
Then add composites:
```typescript
      const compositeRole = await client.roles.findOneByName({name: 'my-service-read'});
      await client.roles.createComposite({roleId: currentRole.id}, [compositeRole]);
```
Does that make sense?
