### ISSUE TITLE
Role name is deleted after call [Update a role by name]

### ISSUE THREAD

**Issue by T-VN** [keycloak/keycloak-nodejs-admin-client#172]
**Describe the bug**
Role name is deleted after call [Update a role by name]

**To Reproduce**
1. What API did you use? => Update a role by name
2. What error message did you see? 

a. send PUT request {{server}}auth/admin/realms/{{realm}}/roles/{roleName}

Request body 
{
        "description": "description",
        "composite": false,
        "clientRole": false
}
b. send GET request {{server}}auth/admin/realms/{{realm}}/roles/{roleName}

**It shows error 404**
{
    "error": "Could not find role"
}

**Expected behavior**
Should get Role normally with updated data

**Enviroment (please complete the following information):**
 - Library Version 5.0

**Comment by edewit** [comment]
you can fix it by adding the role name to the body of your request:
```json
{
  "description": "description",
  "composite": false,
  "clientRole": false,
  "name": "roleName",
}
```
It's a bug in keycloak...
