### ISSUE TITLE
Feature: client scope mappings

### ISSUE THREAD

**Issue by metametadata** [keycloak/keycloak-nodejs-admin-client#18]
**Is your feature request related to a problem? Please describe.**
I currently use `kcadm.sh` to automate creation/deletion of scope mappings:

```
# create
./kcadm.sh create -x "clients/<foo client id>/scope-mappings/clients/<bar client id>" --body "[{\"name\": \"<bar client role name>\"}]"

# list
./kcadm.sh get -x "clients/<foo client id>/scope-mappings/"

# delete
./kcadm.sh delete -x "clients/<...>/scope-mappings/clients/<...>" --body ...
```

In order to migrate to NodeJS I need an API to create and delete scope mappings.

**Describe the solution you'd like**
Have an API for [scope mappings resource](https://www.keycloak.org/docs-api/4.1/rest-api/index.html#_scope_mappings_resource) at `/{realm}/client-scopes/{id}/scope-mappings` (at least `create` and `del`).

**Comment by dschwank** [comment]
Here you go: https://github.com/keycloak/keycloak-nodejs-admin-client/pull/21
We were in the same situation, as we want to automatically configure our keycloak instance.

Maybe you can have a look at the PR!

**Comment by metametadata** [comment]
Thank you, the PR seems to cover the endpoints we need.

**Comment by dschwank** [comment]
If you like, you can use this temporary branch as dependency:

``````

**Comment by zagaria** [comment]
Merged to master and published to npm. Please use 1.13.0 version.
