### ISSUE TITLE
GroupRepresentation doesn't contain attributes

### ISSUE THREAD

**Issue by benjamin658** [keycloak/keycloak-nodejs-admin-client#184]
**Describe the bug**

The interface of the GroupRepresentation contains the `attributes` property, but the actual result doesn't.

Actual result
```
[
  {
    id: 'bc55628f-a667-4f90-a401-6d7be098c126',
    name: 'Foo',
    path: '/Foo',
    subGroups: []
  }
]
```

**To Reproduce**
Simply call `kcAdminClient.groups.find({search: $name})`;

1. What API did you use?
kcAdminClient.groups.find({search: $name});

2. What error message did you see?
No error message.

3. GIve us a minimum code example
KcAdminClient.groups.find({search: $name});

**Expected behavior**
The `groupRepresentation` result should contain the `attributes` property. 

**Screenshots**

**Enviroment (please complete the following information):**
 - OS: [e.g. Ubuntu] OSX
 - Keycloak Version: 12.0.4
 - Library Version: 1.14.18

**Additional context**

**Comment by edewit** [comment]
The find returns a brief version of the group to get the whole group you need to fetch it

```typescript
   kcAdminClient.groups.findOne({id});
```

**Comment by benjamin658** [comment]
Hi @edewit, thanks for your reply.

However, the `briefRepresentation` option doesn't present in the typedef. Is it a bug?

**Comment by edewit** [comment]
ahh yes that is right I'll fix that. as a workaround you can cast:

```typescript
kcAdminClient.groups.find({search: $name, briefRepresentation: false} as unknown as any);
```
or add a `@ts-ignore`
