### ISSUE TITLE
Update feature is not working correctly.

### ISSUE THREAD

**Issue by rajatsehgal2010** [keycloak/keycloak-nodejs-admin-client#19]
If i want to change the user firstname, then i initially fetched the user details
` user = client.users.find('RealmName', {
                username: username
            });`
//above "find" is working. 
`user.firstname = "newFirstName"`
`client.users.update("RealmName", user);`
//but "update" function is not working.

**Comment by wwwy3y3** [comment]
@rajatsehgal2010 Hi
checkout the update example here in test:
(from : https://github.com/keycloak/keycloak-nodejs-admin-client/blob/master/test/users.spec.ts#L87-L95)
```ts
await this.kcAdminClient.users.update(
      {id: userId},
      {
        firstName: 'william',
        lastName: 'chang',
        requiredActions: [RequiredActionAlias.UPDATE_PASSWORD],
        emailVerified: true,
      },
    );
```
