### ISSUE TITLE
would you guys consider to split defs representation between create and update interface

### ISSUE THREAD

**Issue by davide-talesco** [keycloak/keycloak-nodejs-admin-client#191]
IE.
Split RealmRepresentation.ts To: CreateRealmRepresentation.ts and UpdateRealmRepresentation.ts

**Is your feature request related to a problem? Please describe.**
As the create Realm accept a generic RealmRepresentation I will not be warned if say when calling the create I did not set the required realm property, which will cause keycloak to return a 500

Thanks,
Davide

**Comment by edewit** [comment]
Yes the definitions are generated from the Java endpoints using the Java classes as input in Java a `String` is always optional as it can be `null`. There are others that have suggested similar enhancements to the type system for instance by annotating the Java classes with @NotNullable for instance.

**Comment by edewit** [comment]
I've create [KEYCLOAK-19740](https://issues.redhat.com/browse/KEYCLOAK-19740) to address this.
