### ISSUE TITLE
Access Denied - Keycloak.enforcer() doesn't work ?

### ISSUE THREAD

**Issue by Gr0bs** [keycloak/keycloak-nodejs-admin-client#192]
Hi, 
I try to use keycloak with nodejs but I had issues when I try to use keycloack.enforcer. 
First I created my client with "Credential" type and so on. But when I use keycloak.protect() everything work, but not with keycloack.enforcer(). 

So I ask yself why and maybe it's my fault for not configure keycloak correctly.
But when I use you example with the keycloak Realm you provide, this didn't work neither.  

Is there a bug or am I doing something bad ?

**Comment by splimter** [comment]
@Gr0bs 
Did you find a solution where you were able to use the policy enforcer ? if you yes please can you provide more details about it, thanks in advance.
