### ISSUE TITLE
Assign an authentication flow to a client based on flow's name instead of flow's id

### ISSUE THREAD

**Issue by semangard** [keycloak/keycloak-nodejs-admin-client#208]
**Is your feature request related to a problem? Please describe.**
We would like to assign authentication flows to an OIDC client.
The current way _seems_ to use authentication flow's ID, is that correct ? Do you have any test example ?
![image](https://user-images.githubusercontent.com/57065741/129732808-cfa466bc-b1d6-4075-9bb6-90b170d75295.png)

If our assumption is correct, there is an issue because the code thus written cannot be used from scratch to re-create a full env because we cannot guess in advance the ID of the authentication flows.

**Describe the solution you'd like**
It would be better if it could be possible to assign authentication flow's name to an OIDC client  (instead of flow's ID) and get a 'clever' admin client which replaces itself flow's ID by flow's name.

**Describe alternatives you've considered**
Use the Terraform provider to simply do what we expect.
Otherwise code ourself in node.js the required behaviour.

**Comment by edewit** [comment]
You can create a new flow and you get the id of that created flow as a result:

```typescript
const { id } = await adminClient.authenticationManagement.createFlow({alias: 'test', providerId: 'basic-flow', description: '', topLevel: true, builtIn: false});
console.log(id);  // will be something like: f88e49ce-14aa-40d1-b11c-25316b15349c
```
Then you can assign it to a client flow:

```typescript
const client = await adminClient.clients.findOne({ id: clientId });
client.authenticationFlowBindingOverrides.browser = id;
await adminClient.clients.update({ id: clientId }, client);
```

Isn't that easy enough?

**Comment by semangard** [comment]
Hummm, few feedbacks :

a) Yes it can help, but in my case flows are created withing the realm json so I do have simply the flow ID as the result of the creation => I have to write some aditional code to retreive flows ID from their name before assigning these ID to clients, it might more straight forward if I could asign directly flow aliases to clients instead of only flow ID

b) Just a little thing I think you did a mistake, clientId  has to be replaced by client.id

c) I tested it and I have an issue, only the browser flow is correctly assigned
![image](https://user-images.githubusercontent.com/57065741/130514611-3580d306-094f-4afa-b7fa-40c395cdd37a.png)

**Comment by semangard** [comment]
I got it, it was direct_grant and not directGrant....
![image](https://user-images.githubusercontent.com/57065741/130515425-653e240e-1889-4175-b7ef-da5969c0c994.png)

it works now

**Comment by edewit** [comment]
Cool glad it worked
