### ISSUE TITLE
Unable to retrieve authenticationFlows of a realm 

### ISSUE THREAD

**Issue by semangard** [keycloak/keycloak-nodejs-admin-client#209]
**Describe the bug**
According to the doc : https://github.com/keycloak/keycloak-nodejs-admin-client/blob/master/src/defs/realmRepresentation.ts
It should be possible to retrieve the list of authentiocation flows of a realm
![image](https://user-images.githubusercontent.com/57065741/129733230-0b814c87-c3ff-44d9-a60e-2f7f62f56b87.png)

We tried but none flow is found

![image](https://user-images.githubusercontent.com/57065741/129733425-9870d473-5f3f-4eac-9ab7-6b53f19e9921.png)

We check the JSON returned by kcAdminClient.realms.findOne(...), and indeed the attribute _authenticationFlows_ is not found.
We have the issue even if we create a custom flow.

=> Why ?
=> How to get authentication`flows of a realm ?

**Enviroment (please complete the following information):**
We are using:
- the latest version of the the client 
- and KeyCloak 11.0.3

**Comment by edewit** [comment]
To get the authentication flows there is another endpoint:

```typescript
const flows = await kcAdminClient.authenticationManagement.getFlows();

console.log(flows.map(flow => flow.alias)) // this will print  ['browser', 'direct grant', 'registration', 'reset credentials','clients', 'first broker login', 'docker auth', 'http challenge']);
```

**Comment by semangard** [comment]
OK thanks.
