### ISSUE TITLE
Deprecate all packages except @keycloak/keycloak-admin-client

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak-nodejs-admin-client#211]
**Is your feature request related to a problem? Please describe.**
We want to support only a single NPM package instead of publishing multiple ones with different version schemes.

**Describe the solution you'd like**
Use [`npm deprecate`](https://docs.npmjs.com/cli/v7/commands/npm-deprecate) to deprecate the following packages:
- [keycloak-admin](https://www.npmjs.com/package/keycloak-admin)
- [keycloak-nodejs-admin-client](https://www.npmjs.com/package/keycloak-nodejs-admin-client)

The deprecation message should direct people to use the official package [@keycloak/keycloak-admin-client](https://www.npmjs.com/package/@keycloak/keycloak-admin-client).

**Comment by edewit** [comment]
deprecated `keyckoak-admin`, but we are not maintainers of `keycloak-nodejs-admin-client` so we can't deprecate that one

**Comment by jonkoops** [comment]
Looks like nobody depends on it, and since we are not the owner let's close this issue.
