### ISSUE TITLE
Keycloak refresh token

### ISSUE THREAD

**Issue by jstortoise** [keycloak/keycloak-nodejs-admin-client#22]
I am using this plugin for my project and I have some issue with refresh token.

**Describe the bug**
How to refresh token using keycloak-admin-nodejs-client?

**To Reproduce**
1. Authorization
```
const kcAdmin = new KcAdminClient({
    baseUrl: config.KC_BASE_URL,
    realmName: config.KC_REALM_NAME
});
await kcAdmin.auth({
                username: "...",
                password: "...",
                grantType: "password",
                clientId: "...",
                clientSecret: "..."
});
```
2. Get access_token and refresh_token
```
access_token = kcAdmin.getAccessToken();
refresh_token = kcAdmin.refreshToken;
```
3. access_token has 1 hour lifespan and refresh_token has 1 day lifespan. Now, access_token is expired but refresh_token is still available now.

How to get refreshed token? I can get refresh token by using original Keycloak REST API but I'd like to get refresh token by using `keycloak-admin`.

Please someone help me to get refresh token.

> I am sorry, I know this isn't bug but I don't know how to get help from you.

**Comment by jstortoise** [comment]
@justintime4tea , thanks for your response.

Btw, is there any function to get refresh token instead of using another module (panva/node-openid-client) ?

Currently, I am using original keycloak rest api.

```
POST https://<keycloak.domain>/realms/master/protocol/openid-connect/token

{
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    },
    body: {
        grant_type: 'refresh_token',
        client_id: <my_client_id>
        client_secret: <my_client_secret>
        refresh_token: <my_refresh_token>
    }
}
```

Is there any better way to get refresh token?
Also, is there any way to check token valid?

**Comment by evasyuk** [comment]
@jstortoise I've made performed raw HTTP subsequent requests with content exactly like you descibed.

good: access_token has been updated

bad: expires_in and refresh_expires_in fields remains the same and after timeout errors like '400 " Refresh token expired"'

resume: it is not working as expected

solution: as far as you already have clientId/clientSecret, you can obtain access_token as for the first request(I am doing it in plain HTTP request with { grant_type: 'client_credentials',
                client_id: keycloakCfg.clientId,
                client_secret: keycloakCfg.clientSecret,
                scope: 'openid'})

**Comment by cmwylie19** [comment]
are we planning on planning on fixing this anytime soon? I dont understand how this has been an issue for a year and a half. I'm having to convince my client daily not move to aws cognito....

**Comment by cmwylie19** [comment]
Is this even on the agenda to be fixed?

**Comment by mpulido73** [comment]
Never use secrets with **public clients**, justo clientID and refresh_token.

**Comment by BaptisteMonet** [comment]
I can't getAccessToken like you do
I put all the params and the session is open.

I see that there is a getToken inside the auth.js file,
but how to use it, do there is a difference ?
