### ISSUE TITLE
CredentialRepresentation is deprecated

### ISSUE THREAD

**Issue by pommelinho** [keycloak/keycloak-nodejs-admin-client#235]
**Is your feature request related to a problem? Please describe.**
This is the current https://www.keycloak.org/docs-api/15.0/rest-api/index.html#_credentialrepresentation.
However the Type Specification of CredentialRepresentation is deprecated.
Cany you update this?

**Comment by jonkoops** [comment]
> Cany you update this?

@pommelinho What would you like us to do here? Deprecated functionality does not necessarily mean that this API no longer works.
