### ISSUE TITLE
resource type definitions advertise properties that are not supported by the Keycloak REST API

### ISSUE THREAD

**Issue by blevine** [keycloak/keycloak-nodejs-admin-client#236]
There are cases in which the type defs in this client are not supported by the Admin REST API.  Here is one example:

I included a client role mapping in my users.create() call and the role mappings were not created after the successful request.

Looking at the Keycloak server source, I can see that roles are not actually processed.

#49 is another example of this.

This seems to be a generic problem with the Node.js admin client and the REST API.  There's no way to tell from this client's documentation or the REST API documentation or even the client source code which properties in a payload are actually supported by the server.  You have to read the server source code to figure this out.

**Comment by edewit** [comment]
The types are generated based of the Java model and if you looked at the source you'll see that `createUser` takes `UserRepresentation`, also the documentation uses this. So for us there is no easy way to make these types better. Alternative way to see how to use this API is by going to the keycloak admin console and see what requests it is making for the various operations.
