### ISSUE TITLE
ETA for missing KeyCloak features?

### ISSUE THREAD

**Issue by AnandChowdhary** [keycloak/keycloak-nodejs-admin-client#25]
As mentioned in the README, several KeyCloak features are not currently supported:

```md
- Attack Detection
- Authentication Management
- Client Attribute Certificate
- Client Initial Access
- Client Registration Policy
- Client Scopes
- Key
- Protocol Mappers
- Scope Mappings
- User Storage Provider
```

Is there an ETA available for these, or if there are plans to support them?

**Comment by zagaria** [comment]
@AnandChowdhary unfortunately, no. It is a fully open-source project with community support.
