### ISSUE TITLE
keycloak users findMany option

### ISSUE THREAD

**Issue by SameerChorge94** [keycloak/keycloak-nodejs-admin-client#259]
Hello,

I checked for the option to find many users by providing multiple userName or email, but didn't get any.

As per my project requirement i need to fetch the multiple users by the email-Id's and then to update their userAttributes. 

As per with the find One user option we need to make the separate calls for each user for fetcing and then need to update that user's attributes, it's not feasible solution if there are multiple users present at a same time for fetcing keycloak user records.

is there any workaround and solution for same to fetch multiple users information at once and also to update multiple users simultaneously

**Comment by jonkoops** [comment]
You can use the [`Users.find()`](https://github.com/keycloak/keycloak-nodejs-admin-client/blob/master/src/resources/users.ts#L27-L29) method to retrieve a list of users based on a set of filters. The admin client is limited by what the API [supports](https://www.keycloak.org/docs-api/15.0/rest-api/#_getusers).
