### ISSUE TITLE
Error message: "Request failed with status code 401"

### ISSUE THREAD

**Issue by satkamar** [keycloak/keycloak-nodejs-admin-client#28]
const KcAdminClient = require('keycloak-admin').default

async function setupKeycloak(realmName = "**********") {
  try {
    // const keycloakAdmin = new KcAdminClient()
    const keycloakAdmin = new KcAdminClient({
      'baseUrl': "http://localhost:16160/auth",
      'realmName': 'master'
    })

    // Authorize with username / password
    await keycloakAdmin.auth({
      'username': "*******",
      'password': "*******",
      'grantType': 'password',
      'clientId': '*********'
    })
    
    if (realmName) {
      await keycloakAdmin.setConfig({
        'realmName': realmName
      })
    }

    // List all users
    const users = await kcAdminClient.users.find();

    console.log(users)
    
  } catch (err) {
    throw new Error('Keycloak Admin: ' + err)
  }
}

setupKeycloak()

**Screenshots**
![image](https://user-images.githubusercontent.com/16798869/64948768-66ec4e00-d895-11e9-8fd2-75e34c963656.png)

**Enviroment (please complete the following information):**
 - OS: Windows
 - Keycloak Version: 7.0
 - Library Version : 1.12.0

**Comment by flapouille** [comment]
hey, how did you fix that one? Thanks

**Comment by KenG98** [comment]
I'm encountering the same. Also wondering if there was a fix.

**Comment by rekkisomo** [comment]
it should be a crime to close an issue and not give a solution :(

**Comment by harrylepotter-win** [comment]
Did anyone figure out a means of doing this using a public client?
