### ISSUE TITLE
How to use identity provider?

### ISSUE THREAD

**Issue by jstortoise** [keycloak/keycloak-nodejs-admin-client#29]
Hello, I am using facebook and google to my website using keycloak.

I need your help how to use identity providers?

1. How to create user with identity provider?
I don't know how to create with identity provider. So, I created a user with username(test1) and password(test1) manually and added facebook identity provider to the created user.
But I don't think this is the solution to create user with facebook.
I'd like to know how to create user with facebook identity like `signup with facebook` on keycloak.

2. How to login with identity provider?
Even I created user by manually adding facebook identity provider, I can't do keycloak login with identity provider. How to use facebook identity for login?

Please help me.

**Comment by marcus-sa** [comment]
+1 I'm curious about this as well

**Comment by edewit** [comment]
stale issue more a question about how to use keycloak
