### ISSUE TITLE
npm release?

### ISSUE THREAD

**Issue by metametadata** [keycloak/keycloak-nodejs-admin-client#33]
There's a security release 1.12.1 on Github page but it's not published to `npm`. Shouldn't it be published?

**Comment by zagaria** [comment]
Hello @metametadata. It will be published today or tomorrow. Thanks for the reminder!

**Comment by SillyButt** [comment]
Hello! I see you recently added findEvents which I need in my project just in time but it's not published to npm. When are you going to publish master to npm? I don't want to publish it by myself to my private repo if you will update the release soon. Thanks!

**Comment by zagaria** [comment]
@metametadata, @SillyButt  - published new release 1.13.0 with security updates and new features.
