### ISSUE TITLE
TypeError: KcAdminClient is not a constructor

### ISSUE THREAD

**Issue by xCryzed** [keycloak/keycloak-nodejs-admin-client#347]
### Describe the bug

Hi, everyone

if I try to start the script with the following code I'm getting the error: TypeError: KcAdminClient is not a constructor.

```javascript
import KcAdminClient from '@keycloak/keycloak-admin-client';

    const kcAdminClient = new KcAdminClient();
    await kcAdminClient.auth({
        username: username,
        password: password,
        grantType: 'password',
        clientId: 'admin-cli'
    });
```

Do you have any ideas how to fix that?

### Version

16.1.0

### Anything else?

node version: 14.17.0

**Comment by xCryzed** [comment]
Using typescript fixed this.

**Comment by armujahid** [comment]
Facing exact same issue. Package should work without typescript.
