### ISSUE TITLE
Can't join a node under certain conditions

### ISSUE THREAD

**Issue by corradocavalli** [keycloak/keycloak-nodejs-admin-client#349]
### Describe the bug

Consider this group structure https://ibb.co/JxrjMqr looks like a user can't join the Volvo group is already member of cp:admin group despite the "success" message.
The opposite works fine.

### Version

15.0.2

### Expected behavior

Being able to add the user to Volvo group

### Actual behavior

Interface says success but node is not listed among joined.

### How to Reproduce?

Create the same structure, join the same groups using Admin user and try to join Volvo group.

**Comment by jonkoops** [comment]
@corradocavalli  Is this an issue with the API client? This seems more like an issue with Keycloak itself. If you want to report a bug in Keycloak please do so in the respective [issue tracker ](https://github.com/keycloak/keycloak/issues).

**Comment by corradocavalli** [comment]
At the moment only with KC, moved to proper group.
