### ISSUE TITLE
`keycloak-nodejs-admin-client` and `keycloak-nodejs-connect` integration

### ISSUE THREAD

**Issue by nikolay-govorov** [keycloak/keycloak-nodejs-admin-client#38]
I use [keycloak-nodejs-connect](https://github.com/keycloak/keycloak-nodejs-connect) (more precisely, my own fork) for authorization in the project, and I also need to manage roles/permissions.

It would be great if `keycloak-nodejs-admin-client` could use tokens from `keycloak-nodejs-connect`.

**Comment by zagaria** [comment]
@nikolay-govorov please add more details.

**Comment by nikolay-govorov** [comment]
Hello! What kind? How do I use the system, what is the problem, what do I want?

**Comment by zagaria** [comment]
Hello. To clarify - I don't understand your request about tokens. 

https://github.com/keycloak/keycloak-nodejs-connect and https://github.com/keycloak/keycloak-nodejs-admin-client/ have different targets - to protect the server-side application vs administrator management. Or you mean the possibility to pass the user with admin privileges tokens (access token and refresh token) for auth without using username and password in the configuration for keycloak-nodejs-admin-client?

**Comment by nikolay-govorov** [comment]
Yes! We use both possibilities, and we want to transfer access tokens to admin without entering a login/password at ourselves.

**Comment by bwoody3142** [comment]
Hi, I have the same use case here, is there an update on the status of this issue?

**Comment by jonkoops** [comment]
We now allow you to [register](https://github.com/keycloak/keycloak-nodejs-admin-client/blob/de027818f7faaf66c8ac8bbd219c9ca18677a6dd/src/client.ts#L100-L106) a `TokenProvider`, which should be allow you to provide an access token to the Admin Client used for requests.

You can see an example implementation [in the Admin UI](https://github.com/keycloak/keycloak-ui/blob/344131a623592c588b690a62564fdf8fae80ef25/apps/admin-ui/src/context/auth/AdminClient.tsx#L89-L99), where we retrieve the token from Keycloak JS.
