### ISSUE TITLE
Username and password in credentials should be optional

### ISSUE THREAD

**Issue by tristan-fitzgerald-vineti** [keycloak/keycloak-nodejs-admin-client#40]
**Describe the bug**
In the code segment, these two properties are required, but not needed for a `grantType` of `client_credentials`. Making them optional would prevent ide errors that can be misleading.

**Expected behavior**
If I am using a clientId and clientSecret, I shouldn't need to provide the username or password or avoid type errors by using any as a patch. In testing, the auth works without those two properties being set.

**Code Lines**
https://github.com/keycloak/keycloak-nodejs-admin-client/blob/1a94e37d5de05d33dabec971022f6ee0724832f9/src/utils/auth.ts#L7-L8

**Screenshots**
![image](https://user-images.githubusercontent.com/55151723/68827091-7f46d200-0666-11ea-9914-84455c442943.png)

It would be great not to need the any above.

**Comment by galsilb** [comment]
For future reference, using `username: null, password: null ` dose the trick.
