### ISSUE TITLE
Get Multiple Users by Id

### ISSUE THREAD

**Issue by stevehogdahl** [keycloak/keycloak-nodejs-admin-client#403]
### Description

Add an id array to the users.find api so multiple users can be get by ids. Only way to do this now is to call the findOne for each id or findAll and filter the list down.

**Comment by jonkoops** [comment]
Hi @stevehogdahl, this is the repository for the client for the Admin API, not the implementation of the Admin API itself. If you want to request a feature for the Admin API please open an issue on the [main repository](https://github.com/keycloak/keycloak).
