### ISSUE TITLE
misleading 405 error when trying to delete a resource by passing undefined/null resource ID

### ISSUE THREAD

**Issue by claudiunicolaa** [keycloak/keycloak-nodejs-admin-client#427]
### Description

https://github.com/keycloak/keycloak-nodejs-admin-client/blob/main/src/resources/clients.ts#L569
The API returns 405 Method Not Allowed when trying to delete a resource by passing undefined/null resource ID.

I think this behavior is misleading and should be enhanced. What do you think?

**Comment by jonkoops** [comment]
What exactly is the expected behavior here? The `resourceId` parameter is required, so I don't see a reason to make it optional.

**Comment by claudiunicolaa** [comment]
My first thought was that a  400 - Bad request status code is needed, because 405 - Method not allowed is misleading- it tells me the DELET doesn’t exists but I only made a wrong request. 

But I looked again into the codebase and it makes sense to be 405. The DELETE method does not exist for `/{id}/authz/resource-server/resource`. 

Thank you for your time! I will close the issue.
