### ISSUE TITLE
findOne by username returns multiple users in array

### ISSUE THREAD

**Issue by armujahid** [keycloak/keycloak-nodejs-admin-client#461]
### Describe the bug

Create two users with overlapping usernames:
1) 3l@foo.com
2) 33l@foo.com

Call findOne with `3l@foo.com`
```
 const findOneResult = await authClient.users.findOne({
    username:  `3l@foo.com`,
  });
```

### Version

17.0.1

### Expected behavior

it should always return one user (in an Array related: https://github.com/keycloak/keycloak-nodejs-admin-client/issues/78)

### Actual behavior

it is returning both users (because I think it is doing like/not-exact search).

### How to Reproduce?

Check description

### Anything else?

Let me know if anything else is required.

**Comment by jonkoops** [comment]
https://github.com/keycloak/keycloak-nodejs-admin-client/issues/78#issuecomment-732789874

**Comment by armujahid** [comment]
For now I am using find with exact
```
  const findOneResult = await authClient.users.find({
    username,
    exact: true, // don't do like search
  });
```

**Comment by armujahid** [comment]
@jonkoops shouldn't it different from regular find since regular find accepts `UserQuery` while findOne accepts `UserRepresentation` ?

**Comment by edewit** [comment]
@armujahid yes we should update the type it should only accept an id

There are 2 endpoints `/{realm}/users/{id}` and `/{realm}/users/` so if you don't specify an id it just does a search
