### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by fabu-khiarah** [keycloak/keycloak-nodejs-admin-client#47]
Hey @zagaria,

can you release a new version please? I would like to use the changes from my PR soon (https://github.com/keycloak/keycloak-nodejs-admin-client/pull/35)

Thanks in advance :)

**Comment by zagaria** [comment]
Hi @fabu-khiarah 

Yes, of course. I will prepare new release after https://github.com/keycloak/keycloak-nodejs-admin-client/pull/46 and https://github.com/keycloak/keycloak-nodejs-admin-client/pull/43

**Comment by Bessonov** [comment]
hm, this project seems to be not well supported even if community put efforts to creates PRs...

**Comment by zagaria** [comment]
Hi @Bessonov.

This project supported, but for every merge request need review with checking, not just merge :blush:

If you want to help for review and testing merge requests - please let me know.

**Comment by Bessonov** [comment]
@zagaria We need a some additional configuration anyway. So I hope I can come back to your offer :+1:

**Comment by ath88** [comment]
> If you want to help for review and testing merge requests - please let me know.

I'll help. My company uses this, so I have a good reason to want this to work well.

**Comment by bs-matil** [comment]
We also would like to get a new release. Anything one can do?

**Comment by edewit** [comment]
created a new release 1.14 on
