### ISSUE TITLE
users.find() also return their federated identities

### ISSUE THREAD

**Issue by Firjens** [keycloak/keycloak-nodejs-admin-client#475]
### Description

Hello, I've been using this package for some time now but I'd like to see a way to return all users in the `users.find()` function with their federated identities.

I'm not sure if this is already possible but I've been picking my brains for a couple of days now to make it work. I've looked through all the code and issues and I've noticed no issue was opened about this.

Regards.

### Motivation

I'm currently returning a list of all users and making a seperate HTTP request to get their federated identities, this is quite inefficient and can be optimized by returning it with the `users.find()` function.

**Comment by jonkoops** [comment]
Unless this is a feature that is supported by the [Admin API](https://www.keycloak.org/docs-api/18.0/rest-api/index.html#_getusers) this cannot be implemented in the client. If you'd like to add a feature to the Admin API then please file a request on the [main repository](https://github.com/keycloak/keycloak/issues).

From what I can see in the documentation this feature is not supported by the Admin API. Therefore I am closing this issue.
