### ISSUE TITLE
Groups are not included in Response from Keycloak, but in UserRepresentation

### ISSUE THREAD

**Issue by kdankert** [keycloak/keycloak-nodejs-admin-client#49]
When I try to get information from all of my users, the groups property is undefined, so its is not resolved by the keycloak admin rest api response. Is there a way to add the group information to the user endpoint in the keycloak rest api, because it seems to be quite silly to do so much request to keycloak to get every group for each user one by one, when I want to receive the users which are in the realm.  I couldn't find out something about this on the internet, so I decided to open an issue here, as this might be important to other users of keycloak-nodejs-admin-client as well.

**Comment by zagaria** [comment]
Hi @kdankert.

Please provide more details:

1. Keycloak version
2. User profile representation from browser debug console.

Thanks.

**Comment by kdankert** [comment]
I tested this on version 8.0.0, 8.0.0, 8.0.2 and 9.0.0.

Example: User with username `student` and id `6efa3933-aeb1-4114-8678-56d5410be7ec` is in the group `students`

Response from getting all users:
```json
[
    {
      "id": "6efa3933-aeb1-4114-8678-56d5410be7ec",
      "createdTimestamp": 1580740747399,
      "username": "student",
      "enabled": true,
      "totp": false,
      "emailVerified": true,
      "disableableCredentialTypes": [],
      "requiredActions": [],
      "notBefore": 0,
      "access": {
        "manageGroupMembership": true,
        "view": true,
        "mapRoles": true,
        "impersonate": true,
        "manage": true
      }
    },
    {
      "id": "a5fec9bc-581d-4d0e-a434-f8d0d389f2fa",
      "createdTimestamp": 1580740769423,
      "username": "teacher",
      "enabled": true,
      "totp": false,
      "emailVerified": true,
      "disableableCredentialTypes": [],
      "requiredActions": [],
      "notBefore": 0,
      "access": {
        "manageGroupMembership": true,
        "view": true,
        "mapRoles": true,
        "impersonate": true,
        "manage": true
      }
    }
]
```

As you can see the property groups of the User Object which is an array of strings is missing in the response from keycloak-nodejs-admin-client

Response from members of group students:
```json
[
    {
      "id": "6efa3933-aeb1-4114-8678-56d5410be7ec",
      "createdTimestamp": 1580740747399,
      "username": "student",
      "enabled": true,
      "totp": false,
      "emailVerified": true,
      "disableableCredentialTypes": [],
      "requiredActions": [],
      "notBefore": 0
    }
  ]
```

**Comment by kdankert** [comment]
@zagaria Is this helpful to you?

**Comment by kdankert** [comment]
Did you figure out what causes this problem.

**Comment by zagaria** [comment]
Hi @kdankert. 

Sorry for delay - can you, please, provide endpoints that are you using? 

Thanks.

**Comment by kdankert** [comment]
What do you mean by that? 

I did some research and it looks like keycloak doesn't provide the group's in the user representation anymore, because they are two separate entities. So the only option to retrieve it is by doing it for every user manually

**Comment by MRJCrunch** [comment]
@zagaria we use 10.0 version and got the same problem:
```js
/admin/realms/realmname/users/5546dc61-ceb3-4815-bd56-87227be7d9d0/groups
{
    id: 'b61f10b2-8d79-4cb1-a79e-d24cc1750622',
    name: 'foo',
    path: '/foo'
 }
```
```js
/admin/realms/realmname/users/5546dc61-ceb3-4815-bd56-87227be7d9d0
{
    "id": "5546dc61-ceb3-4815-bd56-87227be7d9d0",
    "createdTimestamp": 1616598495051,
    "username": "aaalm",
    "enabled": true,
    "totp": false,
    "emailVerified": false,
    "firstName": "aaalm",
    "lastName": "ef",
    "federationLink": "ebcda658-a824-4801-80bb-e0915980533c",
    "attributes": {},
    "disableableCredentialTypes": [],
    "requiredActions": [],
    "notBefore": 0,
    "access": {
      "manageGroupMembership": true,
      "view": true,
      "mapRoles": true,
      "impersonate": true,
      "manage": true
    }
}
```

**Comment by MRJCrunch** [comment]
And I have the same issue with 12.0.4

**Comment by kdankert** [comment]
I figured out, that this is not the fault of the admin Client. The admin Rest api gives back those results, so I guess keycloak needs a mapper to be configured in order to provide an user's groups.

**Comment by MRJCrunch** [comment]
@kdankert Do you have an example of how to receive groups from users API? I added groups mapper but nothing happens
![image](https://user-images.githubusercontent.com/17198997/112809038-486a3400-9082-11eb-95c6-ba4cd230d0dc.png)

**Comment by kdankert** [comment]
I have not tried it out, cause my application didn't need it anymore. So I unfortunately can't help you with that.

**Comment by blevine** [comment]
This seems to be a common issue with this client. The client advertises support for properties in various payloads which the server doesn't actually support.

**Comment by blevine** [comment]
I'm aware of how to use the API.  The point is that it's very frustrating when you can't believe the documentation or the generated types and you have to look at the server source code.  I realize that this problem originates with the Java class definitions and the REST API documentation

**Comment by edewit** [comment]
@blevine right, it's not a problem of this client, more a problem with how keycloak has defined this admin REST API

**Comment by edewit** [comment]
created issue [KEYCLOAK-19740](https://issues.redhat.com/browse/KEYCLOAK-19740) to address this
