### ISSUE TITLE
Package "react-monaco-editor" not found. Have you installed it? 

### ISSUE THREAD

**Issue by prawee** [keycloak/keycloak-nodejs-admin-client#515]
### Describe the bug

i'm clone and install package already. then while run script it's happen this error

"Package "react-monaco-editor" not found. Have you installed it? "

I'm try install  "react-monaco-editor" but not working

### Version

1.8.2

**Comment by jonkoops** [comment]
I think this issue is reported on the wrong repository. This package does not have a dependency on `react-monaco-editor`, nor any references to it.
