### ISSUE TITLE
Add support for finding groups by their path name

### ISSUE THREAD

**Issue by tbusillo** [keycloak/keycloak-nodejs-admin-client#549]
### Description

The Keycloak API  [supports querying of groups](https://www.keycloak.org/docs-api/18.0/rest-api/#_getgroupbypath) by their path name via `GET admin/realms/{realm}/group-by-path/{path}`. However, the client library currently only supports retrieving groups by their ID (e.g., `GET /{realm}/groups/{id}` via `kcAdminClient.groups.findOne({id: group.id})`. 

I am open to submitting a PR for this, but wanted to check to make sure it is something that may be accepted/included first. 

### Motivation

Currently, we are using this client library to perform all of our service client interactions with the Keycloak API, with the exception of the `group-by-path` functionality (we make a GET request manually currently). 

Internally, we make use of path names and programmatically assign/remove users from groups based upon them. Unfortunately, it is not practical for us to do this via client ID and since the endpoint already exists in Keycloak, supporting it in this client library would be ideal. 

## Proposed Solution

1. Add a new method to the [Realm Admin resource](https://github.com/keycloak/keycloak-nodejs-admin-client/blob/main/src/resources/realms.ts) which makes a `GET` request to `admin/realms/{realm}/group-by-path/{path}`.
2. The method should accept two arguments: `realm: string` (name, not id) and `path: string`.
3. The response type should be `GroupRepresentation`. 

## Psuedo code

```typescript
  public getGroupByPath = this.makeRequest<
    { path: string, realm: string },
    GroupRepresentation
  >({
    method: 'GET',
    path: '/{realm}/group-by-path/{path}',
    urlParamKeys: ['path', 'realm'],
  });
```

**Comment by jonkoops** [comment]
@tbusillo feel free to open up a PR for this. If the Keycloak Admin API supports this then it should be in this library.
