### ISSUE TITLE
Update axios dependency to support HTTP Proxy for HTTPS connection

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak-nodejs-admin-client#58]
The library doesn't work behind a corporate proxy, as axios 0.18.1 always uses HTTPS for HTTP connections. Please see "Fix http adapter to allow HTTPS connections via HTTP" https://github.com/axios/axios/pull/959

Updating axios to latest version > 0.19.0 fixes the problem. I tried it with axios 0.19.2.

**Comment by jbman** [comment]
Axios was updated in https://github.com/keycloak/keycloak-nodejs-admin-client/pull/54
I think this issue could be closed. Is there any release schedule?

**Comment by edewit** [comment]
updated axios to `0.21.0` in the `1.14` release
