### ISSUE TITLE
Add a user count helper

### ISSUE THREAD

**Issue by TomasNiDo** [keycloak/keycloak-nodejs-admin-client#68]
I want to paginate the data when fetching users, the problem is I have to get the total count of users to generate a metadata. Fetching all users and getting its count would defeat the purpose of my pagination.

The solution is obviously getting the count of the users. There is an API available in the [docs](https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_users_resource) where I can get the count of the users, but there is no available helper here in the package.

**Comment by edewit** [comment]
Even a total count of users is to expensive as users can come from external systems like ldap. So there is no total count in the API. You can still paginate, but you can't show the number of pages.
![image](https://user-images.githubusercontent.com/51133/98788145-b75f2d00-2400-11eb-8ae4-ed02b27aadee.png)
This is a screenshot of how we display it in the admin client ^^
