### ISSUE TITLE
Maintenance / project status 

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-nodejs-admin-client#69]
Question to maintainers of this project. Is this project being actively maintained? It looks like there is quite some time since the last release, as well as commits. If this project is not being maintained at the moment, we should look at finding other maintainers or sunsetting the project.

**Comment by zagaria** [comment]
Hi @stianst 

Unfortunately, from my side, I can't provide full support for review and maintain this project.

Good point to find another maintainers that can provide full support.

**Comment by stianst** [comment]
@zagaria thanks for the update, can you send a PR to MAINTAINERS.md to remove yourself from the list of maintainers in that case?

@wwwy3y3 @karlhorky @Schnitzel Any of you actively involved in this project?

**Comment by karlhorky** [comment]
Although I would be able to do some simple reviews and potentially even bug fixes, I don't think that I have enough time to be able to contribute actively enough to this to be able to be called a "maintainer".

I've removed myself in #70.

**Comment by zagaria** [comment]
@stianst removed in https://github.com/keycloak/keycloak-nodejs-admin-client/pull/71

**Comment by stianst** [comment]
@karlhorky @zagaria thanks for the quick response

**Comment by ath88** [comment]
@stianst As I wrote in https://github.com/keycloak/keycloak-nodejs-admin-client/issues/47, I'll be willing to help maintain this. We use Keycloak and Node.js in my organisation, so I would love to give back to the community.

**Comment by stianst** [comment]
@wwwy3y3 @Schnitzel any of you still involved with this project?

**Comment by edewit** [comment]
@stianst how about we use this project to build the new admin console with? Then we can breath new life into this project

**Comment by stianst** [comment]
@edewit if that's beneficial for the new admin console it sounds like a great idea

**Comment by ath88** [comment]
It sounds like a great plan to use for the new admin console. Follows well with [Eating your own dog food](https://en.wikipedia.org/wiki/Eating_your_own_dog_food). How do you propose we go from here?

**Comment by edewit** [comment]
@ath88 created issue #75 and PR #76

**Comment by ath88** [comment]
@edewit Yes - I noticed. But we still need someone to merge it. Preferably someone who can actively maintain the project.

**Comment by edewit** [comment]
@ath88 guess I'm volunteering

**Comment by ath88** [comment]
@stianst Perhaps its time to add a few contributors then? I volunteer too.

**Comment by Schnitzel** [comment]
ugh, sorry didn't see this. 
Actually I also don't really have time to maintain this much longer, therefore removing myself as well.

**Comment by parthibd** [comment]
Is this project going to be abandoned ? There hasn't been any release since last year .

**Comment by edewit** [comment]
No, going to use it to build the new keycloak admin console. See
https://github.com/keycloak/keycloak-admin-ui

**Comment by ath88** [comment]
It is still a valid point @parthibd brings up though. No releases, and quite a few unmerged PRs. Some active maintainers would be great. And - repeating myself - I volunteer if need be.

**Comment by edewit** [comment]
I'm going to do a release later today or early next week, when I get a chance to find out how to do that

**Comment by parthibd** [comment]
@edewit @ath88  Thank you for clearing my doubt . I really love using Keycloak and this library serves our purpose in our company . Happy to hear this is not going to be abandoned. Looking forward to the new admin ui . :)

**Comment by ccravens** [comment]
@edewit would you be able to put me on the list of maintainers as well? This library is extremely important to me and I do not want it to go stale. I also currently have PR awaiting merge and am finding small issues with latest versions of keycloak. Thanks!

**Comment by edewit** [comment]
It's not going stale we are now using it for the new admin console. So everything that can be done with the admin console will get added to this library. Also it's now official part of the keycloak release process

**Comment by edewit** [comment]
@ccravens just open a PR where you add yourself to the maintainers list
