### ISSUE TITLE
findOne by username return array

### ISSUE THREAD

**Issue by DiV666** [keycloak/keycloak-nodejs-admin-client#78]
Hi,

When i use findOne method with username param it's return array of UserRepresentation
```
const user = await kcAdminClient.users.findOne({ username: 'test' });

console.log(user);
[
  {
    "id": "4c1aabe8-8307-404d-818b-721ddc507d44",
    "username": "test",
    ...
  }
]
```
Is this the expected behavior?

When i use findOne with id param, return UserRepresentation Object

**Comment by fmatar** [comment]
This is pretty much applicable to a number of other methods, the array should be converted to a single object instead

**Comment by edewit** [comment]
the way findOne works is when you [specify an id](https://github.com/keycloak/keycloak-nodejs-admin-client/blob/5cc35e0a1964a19ecd3cec61029d5bda64cd0692/src/resources/users.ts#L39-L42) if you don't use an id then it's a regular find.
