### ISSUE TITLE
[Feature] Run tests against multiple relevant Keycloak versions

### ISSUE THREAD

**Issue by ath88** [keycloak/keycloak-nodejs-admin-client#83]
**Is your feature request related to a problem? Please describe.**
Currently, we only test against Keycloak version 7.0.1 as seen here https://github.com/keycloak/keycloak-nodejs-admin-client/blob/master/.travis.yml.

**Describe the solution you'd like**
Utilize travis test matrix to run against multiple versions of Keycloak.

**Describe alternatives you've considered**
I don't see any other way.

**Additional context**
Tests will take significantly longer, but I believe it'll be worth it. I'll supply a PR shortly.

**Comment by ath88** [comment]
This should probably be reopened, since it was moved away from using Travis to use Github Actions instead.

**Comment by edewit** [comment]
Yep your right @ath88 I'll have a look maybe later today

**Comment by ath88** [comment]
@edewit Want a hand with this? If you have a PR coming up, I won't waste my time doing duplicate work. :)

**Comment by edewit** [comment]
Thanks that would be great, I keep posting it as I'm not that familiar with
it
