### ISSUE TITLE
Links to documentation in the readme 404

### ISSUE THREAD

**Issue by Powersource** [keycloak/keycloak-nodejs-admin-client#86]
Several links that are broken, e.g. the "Client" one that links to https://www.keycloak.org/docs-api/4.1/rest-api/index.html#_clients_resource

**Comment by Powersource** [comment]
I think this might be where it actually wants to link https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_clients_resource

Some of the other links also just link back to this repo.

**Comment by edewit** [comment]
fixed in 1.14
