### ISSUE TITLE
ask email for reset password

### ISSUE THREAD

**Issue by BaptisteMonet** [keycloak/keycloak-nodejs-admin-client#88]
**Is your feature request related to a problem? Please describe.**
I want to add email and not id in case of forgot password

**Describe the solution you'd like**
Having the possibility to add email and/or username in place of id from executeActionsEmail

**Describe alternatives you've considered**
None

**Additional context**
I use this api for android an ios application 
so if the user start the application and do not remember is password
 I can't have the id from keycloak without email or username

**Comment by edewit** [comment]
Guess this is an issue for the keycloak rest api, as it doesn't support this.
